on:
  pull_request:
    branches:
      - "main"
  push:
    branches:
      - "*"
    tags:
      - "*"
jobs:
  job1:
    env:
       # refs/tags/v: tag v 開頭是 production
      ENVIORMENT: ${{ startsWith(github.ref, 'refs/tags/v') && 'production' || 'staging' }}
    runs-on: ubuntu-latest
    steps:
      - name: Say hello # name：A name for your step to display on GitHub.
        run: |
          echo "Hello"
          echo "$ENVIORMENT"
          echo "${{env.ENVIORMENT}}"

      - name: Say world # 這個步驟會執行，因為前面的步驟有 continue-on-error: true
        run: echo "World"

      - name: successed
        if: ${{ !failure() }}
        uses: snow-actions/line-notify@v1.1.0
        with:
          access_token: "${{ secrets.LINE_ACCESS_TOKEN }}"
          # tag push event 時，commit message-1 沒有東西，只有 message-2 有資訊，而且連同 commit description 一起顯示
          # commit push event 時，message-1 和 message-1 都有資訊，而且連同 commit description 一起顯示
          # 可以參考 commit_push.png 和 tag_push.png
          message: |
            Successed:
            github.ref_name: ${{ github.ref_name }}
            commit message-1: ${{ github.event.commits[0].message }}
            commit message-2: ${{ github.event.head_commit.message }}
            short commit sha ${{ github.sha }}