on:
  push:
    branches:
      - "*"
    tags:
      - "*"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: step1
        run: echo "step1"
  job2:
    runs-on: ubuntu-latest
    steps:
      - name: step2
        run: echo "step2"
  job3:
    runs-on: ubuntu-latest
    steps:
      - name: step3
        run: echo "step3"
      - name: Try to fail
        run: exit 0 # 可以更改這裡的 exit code 來觸發 job3 失敗
  job4:
    runs-on: ubuntu-latest
    if: ${{ !always() }}
    steps:
      - name: step4
        run: echo "step4"
  nofify_successed:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    if: ${{ always() && !contains(needs.*.result, 'failure') }}
    steps:
      - name: line-notify
        uses: snow-actions/line-notify@v1.1.0
        with:
          access_token: "${{ secrets.LINE_ACCESS_TOKEN }}"
          message: "all jobs have successed"
  nofify_failed:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    if: ${{ always() && contains(needs.*.result, 'failure') }}
    steps:
      - name: line-notify
        uses: snow-actions/line-notify@v1.1.0
        with:
          access_token: "${{ secrets.LINE_ACCESS_TOKEN }}"
          message: "one of jobs has faild"


